##服务配置
server:
  port: 9000
  tomcat:
    max-threads: 800
    uri-encoding: utf-8

##日志配置
logging:
  config: classpath:config/spring/springBoot-logbak.xml

##spring生态配置
spring:
  profiles:
    include: dev-security
  ##应用名
  application:
      name: buukle-cms

  ##http编码
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  ##redis
  redis:
    database: 6
    host: 47.95.13.7
    port: 4376
    password: zxcvbnmKO),.
    pool:
      #最大空闲连接
      max-idle: 100
      #最小空闲连接
      min-idle: 1
      #最大连接数(负数表示没有限制)
      max-active: 1000
      #最大阻塞等待时间(负数表示没有限制)
      max-wait: -1
    timeout: 3000

  ##web - thymeleaf 配置
  thymeleaf:
    cache: false

#clould注册中心 eureka 配置
eureka:
  instance:
    hostname: localhost
    serverport: 8001
  client:
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${eureka.instance.serverport}/eureka/





